# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unplanned' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unplanned
	pod 'Parse'
  pod 'IQKeyboardManagerSwift'
  pod 'GooglePlaces'
  
  # Cocoapods-Keys
  plugin 'cocoapods-keys', {
    :project => "Unplanned",
    :keys => [
      "GoogleAPI"
    ]}

  
  

end
